name: '🚀 Distribute browser extension'
run-name: Distribute Browser extension ${{ github.ref_name }}
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Select the store to deploy to'
        required: true
        default: 'firefox'
        type: choice
        options:
          - firefox
      dryrun:
        description: 'Run in dry mode without publishing'
        required: true
        default: false
        type: boolean
env:
  VITE_BUILD_TARGET: 'extension'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{github.ref_type == 'tag' }}
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # sanad: ref=v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # sanad: ref=v6.4.0
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: 'Build Extension'
        if: ${{ github.event.inputs.target == 'firefox' && matrix.browser == 'firefox' }}
        run: yarn build:firefox

      - name: '⬆️ Upload to Firefox Add-on Store'
        if: ${{ github.event.inputs.target == 'firefox' && matrix.browser == 'firefox' && github.event.inputs.dryrun == 'false' }}
        uses: wdzeng/firefox-addon@b78a4d0148897b072ef18aff65a6bd793e8109be # sanad: ref=v1
        with:
          jwt-issuer: ${{ secrets.WEB_EXT_API_KEY }}
          jwt-secret: ${{ secrets.WEB_EXT_API_SECRET }}
          addon-guid: '{f8793186-e9da-4332-aa1e-dc3d9f7bb04c}'
          xpi-path: firefox_extension.zip
          source-file-path: source_code.zip
